hockeyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')


    

hockeyblog/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from hockeyblog import db
from hockeyblog.models import BlogPost
from hockeyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403) #Unsure if this works

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')

        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Update',
                           form=form)

@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403) #Unsure if it works out

    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')

    return redirect(url_for('core.index'))

hockeyblog/core/views.py
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
	return render_template('index.html')

@core.route('/info')
def info():
	return render_template('info.html')

hockeyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from hockeyblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from hockeyblog.models import User, BlogPost
from hockeyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from hockeyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Logged in successfully.')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
			
    return render_template('login.html', form=form)

@users.route("/logout")
def logout():

    logout_user()
    return redirect(url_for('core.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        print(form)

        if form.picture.data:

            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')

        return redirect(url_for('users.account'))

    elif request.method == 'GET':

        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

@users.route("/<username>")
def user_posts(username):

    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

hockeyblog/templates/account.html
{% extends 'base.html' %}
{% block content %}
	<div class="jumbotron">
		<div align="center">
			<h1>Welcome to {{current_user.username}}'s page</h1>
			<img align='center' src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
		</div>
	</div>

	<div class="container">
		<form method="POST" action="" enctype="multipart/form-data" >
			 
			{{form.hidden_tag()}}

			<div class="form-group">
				{{form.username.label(class='form-group')}}
				{{form.username(class='form-control')}}
			</div>

			<div class="form-group">
				{{form.email.label(class='form-group')}}
				{{form.email(class='form-control')}}
			</div>

			<div class="form-group">
				{{form.picture.label(class='form-group')}}
				{{form.picture(class='form-control')}}
			</div>

			<div class="form-group">
				{{form.submit(class='btn btn-primary')}}
			</div>
			
		</form>
	</div>


{% endblock %}

hockeyblog/templates/base.html
<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" type="text/css" href="http://..../static/style.css">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

	<title>Hockey Blog</title>
</head>
<body>

	<ul class="nav">
		<li id="Home" class="nav-link">
			<a href="{{url_for('core.index')}}">Home</a>
		</li>

		<li class="nav-link">
			<a href="{{url_for('core.info')}}">About</a>
		</li>

		{% if current_user.is_authenticated  %}

		<li class="nav-link">
			<a href="{{url_for('users.logout')}}">Log Out</a>
		</li>

		<li class="nav-link">
			<a href="{{url_for('users.account')}}">Account</a>
		</li>

		<li class="nav-link">
			<a href="#">Create Post</a>
		</li>

		{% else %}

		<li class="nav-link">
			<a href="{{url_for('users.login')}}">Log In</a>
		</li>

		<li class="nav-link">
			<a href="{{url_for('users.register')}}">Register</a>
		</li>

		{% endif %}

	</ul>

	<div class="container">
		{% block content %}
		

		{% endblock %}
	</div>

</body>
</html>

hockeyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">

  <h1>{{post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>

  <p>{{post.text}}</p>

   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>

  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

hockeyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}

<div class="container">

  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}

     </div>

     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

hockeyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
	
	<h1>Hockey Blog</h1>

</div>
{% endblock %}

hockeyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
	
	<h1>Info about the hockey blog</h1>

	<p>More information will be provided here in the future. Stay tuned for updates.</p>

</div>
{% endblock %}

hockeyblog/templates/login.html
{% extends "base.html" %}
{% block content %}
	<form method="POST">
		{{form.hidden_tag()}}
		{{form.email.label}}{{form.email}}<br>
		{{form.password.label}}{{form.password}}<br>
		{{form.submit()}}
	</form>
{% endblock %}

hockeyblog/templates/register.html
{% extends 'base.html' %}
{% block content %}

<div class='container'>
	<form method="POST">
		{{form.hidden_tag()}}

		<div class="form-group">
			{{form.email.label(class='form-group')}}
			{{form.email(class='form-control')}}
		</div>

		<div class="form-group">
			{{form.username.label(class='form-group')}}
			{{form.username(class='form-control')}}
		</div>

		<div class="form-group">
			{{form.password.label(class='form-group')}}
			{{form.password(class='form-control')}}
		</div>

		<div class="form-group">
			{{form.pass_confirm.label(class='form-group')}}
			{{form.pass_confirm(class='form-control')}}
		</div>

		<button type="button" class="btn btn-primary btn-dark">
			{{form.submit()}}
		</button>

	</form>

</div>

{% endblock %}

hockeyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}

<div class='container'>
    <div class='jumbotron'>
        <div align='center'>
            <h1>Welcome to the page for {{user.username}}</h1>
            <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
        </div>
    </div>

{% for post in blog_post.items %}

<h2> <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}"> {{post.title}} </a></h2>
Post was written by: <a href="{{url_for('users.user_post', username=post.author.username)}}"> {{post.author.username}}</a>

<p class='text-muted'> Time published at: {{post.date.strftime("%Y-%m-%d")}}</p>
<br>
    <p>{{post.text}}</p>
<br>
{% endfor %}

</div>

<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if blog_posts.page == page_num %}
            <li class='page-item disabled'>
                <a class='page-link' href='{{url_for("users.user_posts",username=user.username,page=page_num)}}'> {{page_num}} </a>
            </li>
            {% else %}
            <li class='page-item'>
                <a class='page-link' href='{{url_for("users.user_posts",username=user.username,page=page_num)}}'> {{page_num}} </a>
            </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}